### ISSUE TITLE
Problem with the data obtained

### ISSUE THREAD

**Issue by barripdmx** [alvarofpp/network-from-wikipedia#1]
Hi,

I have tried the page https://es.wikipedia.org/wiki/Podemos and I get many references to "Pokemon" that has nothing to do with Podemos. Any solution?

https://drive.google.com/file/d/10Fp31oprrGjJDyS_LYQr0tX-2AgUD1V0/view?usp=sharing

Best regards
Barri

**Comment by alvarofpp** [comment]
Hi @barripdmx .

Did you tried to put "Pokémon" in the STOPS constant in constants.pay?

**Comment by barripdmx** [comment]
Hola @alvarofpp  

Yes. I have put several variables and they are not removed.

SOURCE_URL = 1
SOURCE_TITLE = 2

STOPS = (
    'International Standard Serial Number',
    'International Standard Book Number',
    'National Diet Library',
    'International Standard Name Identifier',
    'International Standard Book Number (Identifier)',
    'Pubmed Identifier',
    'Pubmed Central',
    'Digital Object Identifier',
    'Arxiv',
    'Proc Natl Acad Sci Usa',
    'Bibcode',
    'Library Of Congress Control Number',
    'Jstor',
    'Doi (Identifier)',
    'Isbn (Identifier)',
    'Pmid (Identifier)',
    'Arxiv (Identifier)',
    'Bibcode (Identifier)',
    'Nintendo',
    'Pokemon',
    'Pokémon Chronicles',
    'Pokétoon'
)
